name: Rescan Translation

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'luasrc/**'
      - 'root/**'

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions: write-all

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@main

      - name: Rescan translation
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt -yqq update
          sudo -E apt -yqq install gettext

          curl -LO "https://github.com/openwrt/luci/raw/master/build/i18n-scan.pl"
          curl -LO "https://github.com/openwrt/luci/raw/master/build/i18n-update.pl"
          perl "i18n-scan.pl" . > "po/templates/advancedplus.pot"
          perl "i18n-update.pl" "po"
          find po/ -name '*.po~' -exec rm -f {} \;
          rm -f "i18n-scan.pl" "i18n-update.pl"
          [ -z "$(git status -s)" ] || echo -e "CHANGE_STAT=1" >> "$GITHUB_ENV"

      - name: Commit changes
        if: ${{ env.CHANGE_STAT }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "<github-actions[bot]@users.noreply.github.com>"
          git add .
          git commit -m "chore(po): rescan translation"
          git push -f origin HEAD:main
